spring:
  application:
    name: redis-service
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      httpclient:
        max-header-size: 65536
    instance:
      hostname: ${spring.application.name}.${eureka.instance.instance-id}
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

#server:
#  port: 8079
#  host: localhost
#  servlet:
#    context-path: /redis
#  ssl:
#    key-store: keystore.p12
#    key-store-password: hoangsang236
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#  max-http-request-header-size: 65536

#eureka:
#  instance:
#    securePortEnabled: true
#    securePort: 8079
#    nonSecurePortEnabled: false
#    preferIpAddress: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: https://localhost:8761/eureka/
